services:
  cisco-cli-ref:
    image: nginx:alpine
    container_name: cisco-cli-ref
    restart: unless-stopped
    ports:
      - "8096:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      icon: https://nginx.org/nginx.png
